version: '3.8'

services:

  # Backend App
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgresql:5432/basic_app
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgresql
    networks:
      - my-network

  # PostgreSQL
  postgresql:
    image: postgres:15.2
    restart: always
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - my-network

volumes:
  postgres_data:


networks:
  my-network:
    driver: bridge
