name: Spring Boot Project CI/CD Pipeline

# Actionlar github marketplace

on:
  push:
    branches:
      - master

jobs:
  build-java-app:
    name: Build and Deploy Spring Boot App
    runs-on: ubuntu-latest
    steps:
      # Ilk adim her zaman
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
      - name: Execute Gradle build
        run: ./gradlew --no-daemon clean build
      - name: Build docker image
        run: ./gradlew --no-daemon jibDockerBuild

      - name: Login to Docker Hub
        uses: docker/login-action@v2

        # Tokeni elle github reposuna girecegiz
        with:
          username: ${{ secrets.GD_TOKEN_USERNAME }}
          password: ${{ secrets.GD_TOKEN }}

      - name: Build and Push
        uses: docker/build-push@v4
        with:
          context: .
          dockerfile: Dockerfile
          # Pushlama yapsin mi
          push: true
          tags: ${{ secrets.GD_TOKEN_USERNAME }}/myapp:0.1.0
